runtime: go115

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  min_pending_latency: 15s # max is 15s
  max_pending_latency: 15s # max is 15s

instance_class: F1

handlers:
- url: /.*
  script: auto
